### ISSUE TITLE
Could not find module in path: 'readable-stream/errors'

### ISSUE THREAD

**Issue by harryEth** [ava-labs/avalanchejs#106]
When I updated the `avalanche` to `2.6.2` in the code sandbox project. it throws the error 
`Could not find module in path: 'readable-stream/errors' relative to '/node_modules/readable-stream/lib/internal/streams/state.js'`

It seems like the `avalanche@2.6.2` package is missing some dependencies.

![image](https://user-images.githubusercontent.com/33265609/93769452-a566c800-fbcf-11ea-8683-87fc8e2869b3.png)

**Comment by collincusce** [comment]
I'm told from Farrid that his issue is fixed. It was related to codesandbox looking for the "browser" part of package.json. That part isn't very useful, so we just removed it. Reopen if this isn't true and it didn't fix your issue.

**Comment by harryEth** [comment]
Thanks for looking at this. this is a codesandbox env issue. the solution is here. https://github.com/codesandbox/codesandbox-client/issues/4957
