### ISSUE TITLE
Avalanche Node killed

### ISSUE THREAD

**Issue by minivipers** [ava-labs/avalanchejs#110]
While Avalanche Node continues to bootstrap=true 
node killed because of unknown reasons (the logs in .txt files)
Avalanche version 1.0.1 and running on Ubuntu 18.04 lts on windows 10 pro

[new problem.txt](https://github.com/ava-labs/avalanchejs/files/5332024/new.problem.txt)

**Comment by collincusce** [comment]
Wrong repo: please go to https://github.com/ava-labs/avalanchego . This is the SDK.
