### ISSUE TITLE
RPC calls should be brought into parity with client

### ISSUE THREAD

**Issue by collincusce** [ava-labs/avalanchejs#112]
I just discovered that the client has an RPC call `mintNFT` and `createNFTAsset`. While AJS's support for these functionalities is more robust, we need to stay in-line with the node RPCs. We need to go through the RPCs and make sure they're available in AJS for all VMs.

**Comment by cgcardona** [comment]
Connor reviewed this when he joined and Emre has a PR for the AvalancheGo v1.2.1 addition.
