### ISSUE TITLE
UTXO functionality

### ISSUE THREAD

**Issue by AnasSaeed123** [ava-labs/avalanchejs#113]
When I am using this code:
"let utxos = xchain.getUTXOs(check); " 

It is giving me this Error: connect ECONNREFUSED 127.0.0.1:9650

**Comment by collincusce** [comment]
I don't think this is a getUTXOs problem, but you're not connecting to the node itself. @cgcardona can you reach out and assist?

**Comment by AnasSaeed123** [comment]
const avalanche = require("avalanchejs");
let myNetworkID = 5; //default is 3, we want to override that for our local network
let myBlockchainID = "X"; // The X-Chain blockchainID on this network
let ava = new avalanche.Avalanche("localhost", 9650, "http", myNetworkID, myBlockchainID);
let xchain = ava.XChain();

let addresscheck = ['X-fuji1gkw5z7qw0fn49xn875uyfd9hhcw9fctddvkdru']
getUTXOs(addresscheck);

async function getUTXOs(addresscheck)
{

let utxos = await xchain.getUTXOs(addresscheck);
console.log("Checking utxos: ", utxos);
let sendAmount = new avalanche.BN(100);

let assetid = "U8iRqJoiJm8xZHAacmvYyZVwqQx6uDNtQeP3CQ6fcgQk3JqnK"; //avaSerialized string
let friendsAddress = "X-fuji1acx2e6drpwkyuy5dtfqxt65vygtxd4xse60lwk";
let unsignedTx = await xchain.buildBaseTx(utxos, sendAmount, [friendsAddress], addresscheck, addresscheck, assetid);

}
It is giving me this error: 

"(node:6028) UnhandledPromiseRejectionWarning: Error: Request failed with status code 503
    at createError (/home/alphabet-01/Desktop/anas/javascript/node_modules/avalanchejs/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/alphabet-01/Desktop/anas/javascript/node_modules/avalanchejs/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/alphabet-01/Desktop/anas/javascript/node_modules/avalanchejs/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:6028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6028) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."

**Comment by AnasSaeed123** [comment]
@collincusce I have connected to node but it is giving me above error.

**Comment by cgcardona** [comment]
I'm looking in to this today. I'll keep you posted on what I find @AnasSaeed123. Thanks.

**Comment by cgcardona** [comment]
@AnasSaeed123 the syntax has changed recently. I'll make sure to get the docs updated. Can you try this script? It works for me.

```ts
import { Avalanche} from "avalanche"
let myNetworkID = 5; //default is 3, we want to override that for our local network
let myBlockchainID = "X"; // The X-Chain blockchainID on this network
const avalanche: Avalanche = new Avalanche("localhost", 9650, "http", myNetworkID, myBlockchainID)
let xchain = avalanche.XChain();

let addresscheck = ['X-fuji1gkw5z7qw0fn49xn875uyfd9hhcw9fctddvkdru']
getUTXOs(addresscheck);

async function getUTXOs(addresscheck: string[])
{
  let u = await xchain.getUTXOs(addresscheck);
  let utxos = u.utxos
  console.log("Checking utxos: ", utxos);
  let sendAmount = new BN(100);

  let assetid = "U8iRqJoiJm8xZHAacmvYyZVwqQx6uDNtQeP3CQ6fcgQk3JqnK"; //avaSerialized string
  let friendsAddress = "X-fuji1acx2e6drpwkyuy5dtfqxt65vygtxd4xse60lwk";
  let unsignedTx = await xchain.buildBaseTx(utxos, sendAmount, assetid, [friendsAddress], addresscheck, addresscheck);
}
```

**Comment by AnasSaeed123** [comment]
Okay I'll try it and keep you updated.

**Comment by AnasSaeed123** [comment]
@cgcardona Can it work for this code also: "const avalanche: Avalanche = new Avalanche("api.avax-test.network", 443, "https", myNetworkID, myBlockchainID)"  . Guide me in this case also.

**Comment by AnasSaeed123** [comment]
This API is giving me desired data of utxos. @cgcardona

**Comment by cgcardona** [comment]
Glad to hear that you're getting the proper UTXO data. Try signing your tx like this:

```ts
let unsignedTx = await xchain.buildBaseTx(utxos.utxos, sendAmount, assetid, [friendsAddress], addresscheck, addresscheck);

let tx = unsignedTx.sign(xchain.keyChain())
```

**Comment by AnasSaeed123** [comment]
> Glad to hear that you're getting the proper UTXO data. Try signing your tx like this:
> 
> ```ts
> let unsignedTx = await xchain.buildBaseTx(utxos.utxos, sendAmount, assetid, [friendsAddress], addresscheck, addresscheck);
> let tx = unsignedTx.sign(xchain.keyChain());
> ```

Not getting the desired result by using above code.

**Comment by AnasSaeed123** [comment]
After taking sha256 of serialized transaction data  I have generated signature in C language(Because I am integrating Avalanche in OPOLO Cosmos Hardware wallet in C language) . After that I followed documentation : "https://docs.avax.network/v1.0/en/references/avm-transaction-serialization/#what-signed-transaction-contains" I concatenated unsignedTx and credentials. Is there any API which can issueTx in hex form.

**Comment by AnasSaeed123** [comment]
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32000,
        "message": "problem decoding transaction: invalid input checksum",
        "data": null
    },
    "id": 15
}

Giving this error when sending transcation.

**Comment by AnasSaeed123** [comment]
@cgcardona

**Comment by cgcardona** [comment]
You can call `avm.issueTx` and have the 2nd optional parameter be `encoding`. [More info](https://docs.avax.network/build/apis/exchange-chain-x-chain-api#avm-issuetx)

```curl
curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     : 1,
    "method" :"avm.issueTx",
    "params" :{
        "tx":"6sTENqXfk3gahxkJbEPsmX9eJTEFZRSRw83cRJqoHWBiaeAhVbz9QV4i6SLd6Dek4eLsojeR8FbT3arFtsGz9ycpHFaWHLX69edJPEmj2tPApsEqsFd7wDVp7fFxkG6HmySR",
        "encoding": "hex"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
```

Does that work for you?

**Comment by AnasSaeed123** [comment]
Having problem in signing transaction. Please guide me in this matter. Code given below: 

"const avalanche = require("avalanche");

let myNetworkID = 5; //default is 3, we want to override that for our local network
let myBlockchainID = "X"; // The X-Chain blockchainID on this network
let ava = new avalanche.Avalanche("api.avax-test.network", 443, "https", myNetworkID, myBlockchainID);
let xchain = ava.XChain();

let addresscheck = ['X-fuji1acx2e6drpwkyuy5dtfqxt65vygtxd4xse60lwk']

getUTXOs(addresscheck);

async function getUTXOs(addresscheck)
{
let myKeychain = xchain.keyChain();
let newAddress1 = myKeychain.makeKey();
console.log("Checking data: ", myKeychain);
let utxos = await xchain.getUTXOs(addresscheck);

let sendAmount = new avalanche.BN(1);
let assetid = "U8iRqJoiJm8xZHAacmvYyZVwqQx6uDNtQeP3CQ6fcgQk3JqnK"; //avaSerialized string
let friendsAddress = "X-fuji1gkw5z7qw0fn49xn875uyfd9hhcw9fctddvkdru";
let unsignedTx = await xchain.buildBaseTx(utxos.utxos, sendAmount, assetid, [friendsAddress], addresscheck, addresscheck);
console.log("Checking unsignedTx: ", unsignedTx);
console.log("Checking unsignedTx.transaction: ", unsignedTx.transaction);

console.log("Checking : ", xchain.keyChain());
//let signedTx = unsignedTx.sign(myKeychain);
let signedTx = unsignedTx.sign(xchain.keyChain());

}"

**Comment by AnasSaeed123** [comment]
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32000,
        "message": "problem decoding transaction: invalid input checksum",
        "data": null
    },
    "id": 1
}

**Comment by AnasSaeed123** [comment]
No, I am having an issue in signing transactions. Sorry for the late reply.

**Comment by cgcardona** [comment]
Has this been resolved or have you made progress?

**Comment by AnasSaeed123** [comment]
No, not yet. It is still pending.

**Comment by collincusce** [comment]
Have you looked at the examples to see if there's any hints what's going on?

https://github.com/ava-labs/avalanchejs/tree/master/examples

**Comment by bryanwb** [comment]
I am hitting the same issue signing a transaction

`let tx = unsignedTx.sign(xchain.keyChain());`
generates the error
```
/home/hitman/pr/yo/node_modules/src/apis/avm/basetx.ts:166
        const signval: Buffer = keypair.sign(msg)
                                        ^
TypeError: Cannot read property 'sign' of undefined
```
xchain has my keypair loaded.

W/out being able to sign a transaction, I can't create an asset, the most basic use case for avalanchejs. Halp :(

**Comment by paOol** [comment]
hopefully you can find what you are lookig for by going through the tests for `tx` and `utxo`s below.

https://github.com/ava-labs/avalanchejs/blob/master/tests/apis/avm/tx.test.ts
https://github.com/ava-labs/avalanchejs/blob/master/tests/apis/avm/utxos.test.ts

closing due to age.
