### ISSUE TITLE
Wrong return type.

### ISSUE THREAD

**Issue by kanatliemre** [ava-labs/avalanchejs#128]
https://github.com/ava-labs/avalanchejs/blob/4d54fb15b514c28594bbf6d07be2de0a45211412/src/apis/platformvm/api.ts#L896

The returned type for numFetched should be a number but the api result is a string.

https://github.com/ava-labs/avalanchejs/blob/4d54fb15b514c28594bbf6d07be2de0a45211412/src/apis/platformvm/api.ts#L936

Maybe parse the response and return an int?

**Comment by cgcardona** [comment]
Resolved
