### ISSUE TITLE
Redundant?

### ISSUE THREAD

**Issue by kanatliemre** [ava-labs/avalanchejs#152]
I noticed that `buildImportTx` method actually gets the utxos from the node. Isn't this redundant since `utxoset` is already given as a parameter?

https://github.com/ava-labs/avalanchejs/blob/70413e86dbad0ff122d2e00e403d667d3ba8a22d/src/apis/avm/api.ts#L880

**Comment by collincusce** [comment]
No it gets the atomic UTXOs which is on a different chain from the passed in `utxoset`. So for instance, if you're importing from a P-Chain, your source chain would be P-Chain and the getUTXOs call will get utxos that originate from the P-Chain only. The passed in utxoset isn't the set of atomicUTXOs.

**Comment by cgcardona** [comment]
Closing since Collin answered
