### ISSUE TITLE
Compute transaction ID before broadcasting

### ISSUE THREAD

**Issue by faustbrian** [ava-labs/avalanchejs#154]
Is it currently possible to compute the transaction ID before calling `issueTx`? I am working on an integration and currently have to generate UUIDs to keep track of the transactions because I don't see any way of getting a transaction ID before broadcasting it.

**Comment by EvanJRichard** [comment]
Yes! Will add. In the meantime, for X-chain, P-chain, and atomic C-chain interactions, you can compute the sha256 of the final signed transaction bytes - that'll be the txid. See also: https://github.com/ava-labs/avalanchego/blob/master/vms/components/avax/metadata.go#L26

**Comment by faustbrian** [comment]
Thanks, will manually do that in the meantime.

**Comment by paOol** [comment]
with the `unsignedTx` you can compute the transaction ID like so;

```

  import createHash from "create-hash"
  import { Serialization } from "../../src/utils"

 const serialization: Serialization = Serialization.getInstance()
 const cb58: SerializedType = "cb58"


  const unsignedTx: UnsignedTx = new UnsignedTx(baseTx)
  const tx: Tx = unsignedTx.sign(xKeychain)
  const buffer: Buffer = Buffer.from(
    createHash("sha256").update(tx.toBuffer()).digest().buffer
  )
  const txid: string = serialization.bufferToType(buffer, cb58)
  ```
