### ISSUE TITLE
Client configuration options

### ISSUE THREAD

**Issue by sosedoff** [ava-labs/avalanchejs#156]
Hi all, 

I have been looking through a bunch of docs and source code and would appreciate some input on the following topics/improvements to the JS package:

- Provide a base path for all API endpoints, ie Avalanche services are available on `/my/fancy/prefix`, example: `/my/fancy/prefix/ext/info`. From the docs/code it seems like its possible to configure for specific clients, like AVM, but not possible for the `new avalanche.Avalanche` call. Maybe add another top level constructor like `new avalanche.AvalancheFromURL('https://myhost.com/api/prefix`) so its easier to initialize.
- Ability to pass extra headers for all API calls. Similar to `setAuthToken` call which sets internal bearer authentication but for other general purpose headers. Example: `avalancheClient.setHeader('X-Api-Auth', 'foobar')`. This will allow access to nodes running behind API gateways, etc.

Thanks!

**Comment by cgcardona** [comment]
Can you help me understand exactly what you'd like for the first point? Does this accomplish what you need?

```ts
const host: string = "myhost.com/api/prefix"
const port: number = 9650
const protocol: string = "https"
const networkID: number = 12345
const avalanche: Avalanche = new Avalanche(host, port, protocol, networkID)
```

I merged [this PR](https://github.com/ava-labs/avalanchejs/pull/166) which allows instantiating `Avalanche` with `undefined` as the `port`.  It properly creates the `baseURL` w/out the `:port` which I think might be what you’re looking for.

```ts
const ip: string = 'ava-mainnet.gateway.pokt.network/v1/6024534be1261e00308bfa38';
const protocol: string = 'https';
const networkID: number = 1;
const avalanche: Avalanche = new Avalanche(ip, undefined, protocol, networkID);
```

**Comment by sosedoff** [comment]
@cgcardona yep, this will do!

**Comment by cgcardona** [comment]
Excellent! Closing issue. Please feel free to reopen or create a new issue as needed. 🎩
