### ISSUE TITLE
parseAddress usage

### ISSUE THREAD

**Issue by gitloverr** [ava-labs/avalanchejs#204]
hi everyone,

How can I convert  an address to buffer format? I'm using parseAddress method but it returns as undefined:

I used it like this: 

const BinTools = require("avalanche").BinTools
let bintools = BinTools.getInstance() 

bintools.parseAddress("fuji1vq03amrqkysuq38rcth75zkzu0c6j7yncw8xsz","2JVSBoinj9C2J33VntvzYtVJNZdN2NKiwwKjcumHUWEb5DbBrm")

how can I use it?

thank you

**Comment by cgcardona** [comment]
You want to use `bintools.stringToAddress` to convert a `string` to a `Buffer` and `bintools.addressToString` to convert a `Buffer` to a `string`.

```ts
const addressBuffer: Buffer = bintools.stringToAddress(keypair.getAddressString())
// <Buffer e4 1e 2c 18 2d d4 9a 83 12 7a dc ce 18 a6 a5 ec 4c 5e f0 c8>
const addressString: string = bintools.addressToString(hrp, chainID, addressBuffer)
// X-local1us0zcxpd6jdgxyn6mn8p3f49a3x9auxg69rn9x
```

Here's a [full working example](https://gist.github.com/cgcardona/c0eb988b9e32594be0f6dd3eabc9cdcd).

**Comment by cgcardona** [comment]
Here are the docs

* [addressToString](https://github.com/ava-labs/avalanche-docs/blob/51d6c645d7de71a23082bab0be63be0dc5f83bc0/build/tools/avalanchejs/classes/utils_bintools.bintools.md#addresstostring)
* [stringToAddress](https://github.com/ava-labs/avalanche-docs/blob/51d6c645d7de71a23082bab0be63be0dc5f83bc0/build/tools/avalanchejs/classes/utils_bintools.bintools.md#stringtoaddress)
