### ISSUE TITLE
physical path error

### ISSUE THREAD

**Issue by veridelisi** [ava-labs/avalanchejs#231]
my avalanchejs is in the /home/node_modules/avalanche, I try to execute "test" codes for avm modules [nevertheless](url) there are errors in physical paths
What is the problem?

![55](https://user-images.githubusercontent.com/72710290/122724720-e4b86700-d27c-11eb-9398-97e11d00ec5d.png)

**Comment by veridelisi** [comment]
cannot find module ts2307

**Comment by cgcardona** [comment]
I just tested and this is working for me

```zsh
ts-node examples/avm/getAllBalances.ts
[ { asset: 'AVAX', balance: '300000000000000000' } ]
```

`npm run build` is also working for me. What node version are you using? It should be >=14.17.0.

**Comment by cgcardona** [comment]
Ping @veridelisi can you confirm that this is still an issue?

**Comment by paOol** [comment]
These are resolved in my unit test PR.

closing.
