### ISSUE TITLE
How could I get ALL transactions of any x chain address datas as avascan type ?

### ISSUE THREAD

**Issue by veridelisi** [ava-labs/avalanchejs#232]
Hello
I would like to get all transactions of one x chain address as avascan shows us ?

**Received**
Received.inputs
Received.outputs

**Sent**
Sent.inputs
Sent.outputs

Sincerely

**![77](https://user-images.githubusercontent.com/72710290/122728192-8a210a00-d280-11eb-806a-0c4269b0d79c.png)**

**Comment by cgcardona** [comment]
Try [Ortelius's getTransaction method](https://docs.avax.network/build/tools/ortelius#get-transaction)

**Comment by veridelisi** [comment]
Get Transaction

**Find a single transaction by its ID.**
I have 4400 transactions
