### ISSUE TITLE
Problems deserializing a delegation Tx

### ISSUE THREAD

**Issue by jpop32** [ava-labs/avalanchejs#243]
So, I have a Delegate tranasaction that I'm trying to deserialize:
`11111GtDqZrpUsnpdupvserXCGeCRdu6JMcVEgTBHLAvyVbRGsLSAuVMqvvqJkojg3VepcnrZ6r2AF6FQLd4WMx6PNRtX7ATt3TGkYbQ14suwRuy6YtLMR9X2wZt1h7mUy9iTiVyQ168tko4A1bNdHsbbuXw3EJ9wdrVGuanQoGHxJV54nqegNf4HPPB8NoNAZ1QiS7yreoTwuhknTsGpFq5XqQkiUPbunsEsS615o8nRgtjao6kaYRP1ExnVmgKZQ1VPZrfKvtmu2tcyeVFHsxAJ1nKEJwjXA32p1NJq3SCry9CXp7cgqCp7r9iRDzstJoT5Fr8BPh8HUYPEYoyiTx5Bx4nKWRgNQGN9tAHCenjX9QL3tKEin48GTHK1PrGVDMSGDeZdm4ybxvhPcFWp7o29AcjTdnoj4mEMWNZ5FRKGraVaaRuCYDC1FkZJcTLfQujH82smnF7iNU4So4fDV8DXbv4mEpvzAmQYvYJxxyDsRUHAo6auXfVK2pZrSF1StdHQdgq6S1sTqFy1h7mk7ufVMiRZkUj5g1gGPTZn5HDMtBjdRAnfdvr8ChNDcYGCjkAmiV3DVcKGxQq66DFtopP4qSMagJ59vvnpbeXiRhX1M9ME7dkbafbUnKakJtmG` into `AddDelegatorTx`

Relevant bit of code is here:
```
const sTxBuffer = await pchain.getTx("W7kr2JghssEPKYdWVfztcukyerDMyADwwX9dB9FPz5n8KUqbp")
const serialization: Serialization = Serialization.getInstance()
const bufTx = serialization.typeToBuffer(sTxBuffer,"cb58")
const validateTX: AddDelegatorTx = new AddDelegatorTx()
validateTX.fromBuffer(bufTx)
```
If fails on the `fromBuffer` line with the error:

`RangeError: Trying to access beyond buffer length`

This is all running on Fuji, using the latest v3.7.0.

The transaction is real, and can be seen [here](https://explorerapi.avax-test.network/v2/transactions/W7kr2JghssEPKYdWVfztcukyerDMyADwwX9dB9FPz5n8KUqbp)

**Comment by cgcardona** [comment]
Here is the pattern for properly parsing these bytes into an `AddDelegatorTx`

```ts
import { BinTools, Buffer } from "../../src"
import {
  Tx,
} from "../../src/apis/platformvm"

const bintools: BinTools = BinTools.getInstance()
const bytes: string = "11111GtDqZrpUsnpdupvserXCGeCRdu6JMcVEgTBHLAvyVbRGsLSAuVMqvvqJkojg3VepcnrZ6r2AF6FQLd4WMx6PNRtX7ATt3TGkYbQ14suwRuy6YtLMR9X2wZt1h7mUy9iTiVyQ168tko4A1bNdHsbbuXw3EJ9wdrVGuanQoGHxJV54nqegNf4HPPB8NoNAZ1QiS7yreoTwuhknTsGpFq5XqQkiUPbunsEsS615o8nRgtjao6kaYRP1ExnVmgKZQ1VPZrfKvtmu2tcyeVFHsxAJ1nKEJwjXA32p1NJq3SCry9CXp7cgqCp7r9iRDzstJoT5Fr8BPh8HUYPEYoyiTx5Bx4nKWRgNQGN9tAHCenjX9QL3tKEin48GTHK1PrGVDMSGDeZdm4ybxvhPcFWp7o29AcjTdnoj4mEMWNZ5FRKGraVaaRuCYDC1FkZJcTLfQujH82smnF7iNU4So4fDV8DXbv4mEpvzAmQYvYJxxyDsRUHAo6auXfVK2pZrSF1StdHQdgq6S1sTqFy1h7mk7ufVMiRZkUj5g1gGPTZn5HDMtBjdRAnfdvr8ChNDcYGCjkAmiV3DVcKGxQq66DFtopP4qSMagJ59vvnpbeXiRhX1M9ME7dkbafbUnKakJtmG"
const bytesBuf: Buffer = bintools.cb58Decode(bytes)

const main = async (): Promise<any> => {
  const tx: Tx = new Tx()
  tx.fromBuffer(bytesBuf)
  console.log(tx)
}

main()
```
