### ISSUE TITLE
Headers typo in v3.8.0

### ISSUE THREAD

**Issue by guillaumegaluz** [ava-labs/avalanchejs#244]
https://github.com/ava-labs/avalanchejs/commit/87019e2585800513650feb0857f3245dae393769#diff-8582ed8cd62f358b651ff1b5a6935c322da213407e22cf835959834baf4d4f77L137

<img width="659" alt="Screen Shot 2021-07-09 at 4 17 46 PM" src="https://user-images.githubusercontent.com/206753/125131727-352f2180-e0d1-11eb-8853-8220fcfe6df1.png">

2 occurences

Reported by a user going through the [Avalanche Pathway](https://learn.figment.io/network-documentation/avalanche/tutorials/pathway/1.-connect-to-avalanche-node-with-datahub) on Figment Learn. We downgraded to `3.7.0` for now and it fixed the issue

**Comment by cgcardona** [comment]
Fixed in [v3.8.1](https://github.com/ava-labs/avalanchejs/releases/tag/v3.8.1). Great catch. Thank you very much 🎩
