### ISSUE TITLE
Replace `jest`

### ISSUE THREAD

**Issue by dhrubabasu** [ava-labs/avalanchejs#250]
Jest is great... but it's very slow at the same time.

I've been finding https://github.com/lukeed/uvu to be an excellent framework that's very extensible. 

It also integrates with `c8` and/or `nyc` so we could explore adding code coverage to avalanchejs.

**Comment by cgcardona** [comment]
Can you create a small prototype of this? Wondering if there are any syntax change implications or if this is just a plug-and-play replacement.

**Comment by dhrubabasu** [comment]
It probably won't be plug-and-play but the modifications shouldn't be too extensive.

I use it in https://github.com/pangolindex/pangolin-api.

To run the tests, it's `uvu -r ts-node/register tests -i setup`. For a sample test file: https://github.com/pangolindex/pangolin-api/blob/main/tests/index.ts.

**Comment by paOol** [comment]
adding to 4.0 thread and closing this issue
