### ISSUE TITLE
AvalancheJS 4.0 features

### ISSUE THREAD

**Issue by cgcardona** [ava-labs/avalanchejs#260]
Capturing ideas for AvalancheJS 4.0.

* `data.error` should throw ?
* [Remove `/dist` from import path](https://github.com/ava-labs/avalanchejs/issues/267)
  * [Edit src/index.ts](https://github.com/ava-labs/avalanchejs/blob/master/src/index.ts)
* [Move to ESM](https://github.com/ava-labs/avalanchejs/issues/237)
* Switch default branch from `master` to `main`
* Remove the [ip property](https://github.com/ava-labs/avalanchejs/blob/master/src/avalanche.ts#L25) and [getIP](https://github.com/ava-labs/avalanchejs/blob/master/src/avalanche.ts#L73) in favor of [host](https://github.com/ava-labs/avalanchejs/blob/master/src/avalanche.ts#L27) and [getHost](https://github.com/ava-labs/avalanchejs/blob/master/src/avalanche.ts#L68)
* Return interfaces for RPC calls instead of `Promise<object>`

**Comment by dhrubabasu** [comment]
#237 will be a breaking change so should be reserved for 4.0

**Comment by yulin-dong** [comment]
Re-organize and split AvalancheJS into smaller packages to make them easy to be imported.

**Comment by dhrubabasu** [comment]
Accommodate dynamic fees:
https://github.com/ava-labs/avalanchejs/blob/master/src/utils/constants.ts#L312
https://github.com/ava-labs/avalanchejs/blob/master/src/utils/constants.ts#L170

Would probably need to incorporate calling `eth_gasPrice` and providing options for low, medium, and high priority transactions (akin to geth)

**Comment by paOol** [comment]
Almost everything is a class, when some should not be.

Functional components (where it makes sense) can result in fewer lines of code for the developer, and make things easier to read (subjective).

**Comment by paOol** [comment]
instead of 
```
  const networkID: number = 12345
  const ip: string = "127.0.0.1"
  const port: number = 9650
  const protocol: string = "https"
  const avalanche: Avalanche = new Avalanche(
    ip,
    port,
    protocol,
    networkID,
    undefined,
    undefined,
    undefined,
    true
  )

// and having to do this everytime
const blockchainID: string = Defaults.network[networkID].X.blockchainID
const avaxAssetID: string = Defaults.network[networkID].X.avaxAssetID
```

we could include the defaults and do something like

`const avalanche: Avalanche = new Avalanche.mainnet()`
`const avalanche: Avalanche = new Avalanche.local()`
`const avalanche: Avalanche = new Avalanche.testnet()`

`console.log(avalanche.avaxAssetID) // FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z`

`console.log(avalanche.blockchainID) // 2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM`

**Comment by MrHell0** [comment]
Having to work w/ different UTXOsets is a pain compared to using the C-chain's account model.

I would love to do this 

```
const xchain = Avalanche.fromMnemonic('hello foo ...', Avalance.MAINNET);
console.log(xchain.balance())
xchain.send(0x1111..., 1)
```

**Comment by iFrostizz** [comment]
Would love that `getTxStatus()` function emit some EventEmitter to track the transactions status asynchronously

**Comment by ramilexe** [comment]
@iFrostizz 

https://github.com/ava-labs/coreth/pull/168

It is a little different, but allows you to subscribe to transaction on c-chain

**Comment by paOol** [comment]
adding https://github.com/ava-labs/avalanchejs/issues/250  as a 4.0 roadmap item and closing out the other issue.

same for https://github.com/ava-labs/avalanchejs/issues/237 .

same for https://github.com/ava-labs/avalanchejs/issues/262.

**Comment by cgcardona** [comment]
Remove the [`ip` property](https://github.com/ava-labs/avalanchejs/blob/master/src/avalanche.ts#L22) and the [`getIP` method[(https://github.com/ava-labs/avalanchejs/blob/master/src/avalanche.ts#L60-L63)

**Comment by dhrubabasu** [comment]
We should look into removing feross's `buffer` module and replacing it with the native `TextEncoder` and `TextDecoder`. This helper will streamline the removal: https://github.com/lukeed/worktop/blob/next/src/buffer.ts. We'll need to import it from the util lib for Node.js compatibility.
