### ISSUE TITLE
Websocket refactoring

### ISSUE THREAD

**Issue by cgcardona** [ava-labs/avalanchejs#261]
Refactor from one-stop solution to helper library similar to how ethers.js handles websockets.

**Comment by dhrubabasu** [comment]
This issue refers to https://github.com/ava-labs/avalanchejs/blob/master/src/apis/socket/socket.ts.

In general, we should avoid enforcing certain dependencies on being used. The file above is a thin wrapper on top of `isomorphic-ws` which seems like an odd addition to this library.

**Comment by paOol** [comment]
closing and consolidating into the Avalanche 4.0 thread
