### ISSUE TITLE
VSCode debugging broken 

### ISSUE THREAD

**Issue by cgcardona** [ava-labs/avalanchejs#262]
It's possible to create a separate file and debug/step into AvalancheJS but not currently possible to set breakpoints directly in the code under examples dir in AvalancheJS (e.g. examples/info/peers.ts). IIRC this worked when I first joined the team so some change introduced a regression since then.

**Comment by paOol** [comment]
After spending some time on this issue, I think it makes sense to resolve this after  https://github.com/ava-labs/avalanchejs/issues/267

because the configuration would likely need to be changed again after that issue.

**Comment by paOol** [comment]
adding to 4.0 thread and closing this issue.
