### ISSUE TITLE
Resolve eslint warnings

### ISSUE THREAD

**Issue by cgcardona** [ava-labs/avalanchejs#264]
## Summary

There are currently 249 eslint warnings which fall into the 3 categories below.

* [Generic Object Injection Sink](https://github.com/nodesecurity/eslint-plugin-security/blob/master/docs/the-dangers-of-square-bracket-notation.md)
* Function Call Object Injection Sink
* Variable Assigned to Object Injection Sink

## Next Steps

ESLint can throw a bunch of false positives. So we need to triage each warning. If the warning is false positive we can have ESLint ignore like so

```ts
// Before
return this.types[value]

// After
return this.types[value] /* eslint-disable-line */
```

**Comment by paOol** [comment]
`  return this.types[value.toString()];` 
would also resolve the Generic Object Injection Sink warning.

**Comment by cgcardona** [comment]
Yea, that's a workable solution but eslint I think is throwing a bunch of false positives. We actually have to triage each warning and see if it's just noise or if we need to implement the pattern you pointed out. It's tedious but needed per that doc I linked. 

It's not our highest priority atm. We can circle back to it. Plus I suspect once we understand what the false positives look like we should be able to resolve it pretty quickly.
