### ISSUE TITLE
Refactor directory structure of built package

### ISSUE THREAD

**Issue by cgcardona** [ava-labs/avalanchejs#267]
* Remove `/dist` from the import path.
* Edit [src/index.ts](https://github.com/ava-labs/avalanchejs/blob/master/src/index.ts)

I captured it in it’s own issue as well as in [the AvalancheJS v4.0 feature list](https://github.com/ava-labs/avalanchejs/issues/260) though it’s potentially possible to do this in a backward compatible manner

**Comment by paOol** [comment]
closing and consolidating into the Avalanche 4.0 thread
