### ISSUE TITLE
Custody Verification

### ISSUE THREAD

**Issue by UMANGAWASTHY** [ava-labs/avalanchejs#295]
Hi Team
i am using avalanche-rosetta node, now i like to implement custody verification.
can i perform custody verification on rosetta server? if yes, please provide document/example.

Thanks

**Comment by cgcardona** [comment]
What do you mean by custody verification?

**Comment by paOol** [comment]
duplicate of https://github.com/ava-labs/avalanche-rosetta/issues/26
and outside of the scope of this repo.

closing.
