### ISSUE TITLE
Is node setup is necessary to work with KeyPair class functions getAddressString, sign and verify.

### ISSUE THREAD

**Issue by UMANGAWASTHY** [ava-labs/avalanchejs#323]
Hi Team 
My requirement is to generate publickey/addresses, perform sign & verify operations using avalanchejs library.
**Is node setup is necessary to work with KeyPair class functions.**

**Comment by paOol** [comment]
`KeyChain` and `KeyPair` do not require your own node in order to generate addresses.

`Keystore` however, is not enabled on the public API nodes.
