### ISSUE TITLE
keypair class Verify function not working as excepted after node restart. 

### ISSUE THREAD

**Issue by UMANGAWASTHY** [ava-labs/avalanchejs#324]
Hi Team
I am working on sign and verify function of keypair class.

**Case -1 -> Here my code**
import { Avalanche, BinTools, BN, Buffer } from "avalanche"
const bintools = BinTools.getInstance()
const myNetworkID = "1" 
const avalanche = new Avalanche("127.0.0.1", 9650, "http", myNetworkID)
const main = async () => {
  const cchain  = avalanche.XChain
  const myKeychain = cchain.keyChain();
  const keypair = myKeychain.makeKey() 
  const addressString = keypair.getAddressString() 
  const pubkstr = keypair.getPublicKeyString() 
  const privkstr = keypair.getPrivateKeyString
  const message = Buffer.from("AvalancheTest");
  const signature = bintools.cb58Encode(keypair.sign(message)) 
  const IsVerify = keypair.verify(message, bintools.cb58Decode(signature)) 
};
main();

**>node myclass, O/p -**

AddressString – 2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM-custom1jwfq2w4afd3t7jdghnked77h6d4qmvcysdws9u
PublicString - 5PHVbdZqAeuqMdWTCCp7JCWb399AUnrtBePUf2qEzxJkoqG2pE
PrivateString - PrivateKey-6UGm6ZB62ovn6gyoaXcYEH6kP8ik9Fy46LrKqb5Rdbhy4SVnE
Signature -  zkTUQ8ARak5q1XFgLTojEWXGXM8FFuhzQss9PP5bobcZMwCWQ1EDNfiRyKUacJXQ4rmJ8uYHcnvKARK7gmaeRWg2Q5Hokc
IsVerify- True

**As for output, it’s working fine.**

**Now I restart node passing values of Signature and PublicStr from Case-1 o/p.
Here is my code**

import { Avalanche, BinTools, BN, Buffer } from "avalanche"
const bintools = BinTools.getInstance()
const myNetworkID = "1" 
const avalanche = new Avalanche("127.0.0.1", 9650, "http", myNetworkID)
const main = async () => {
  const cchain  = avalanche.XChain() //returns a reference to the C-Chain used by AvalancheJS
  const myKeychain = cchain.keyChain();
  const keypair = myKeychain.makeKey() // returns an instance of the KeyPair class
  const pubkey  = "5PHVbdZqAeuqMdWTCCp7JCWb399AUnrtBePUf2qEzxJkoqG2pE";
  const signature  = "zkTUQ8ARak5q1XFgLTojEWXGXM8FFuhzQss9PP5bobcZMwCWQ1EDNfiRyKUacJXQ4rmJ8uYHcnvKARK7gmaeRWg2Q5Hokc";
  const messagestr  = "AvalancheTest";
  const message = Buffer.from(messagestr);
  const IsVerify = keypair.verify(message, bintools.cb58Decode(signature))
};
main();
**>node myclass, O/p -**
IsVerify – False

**Now here I am excepting, isverify should be true.**

**Comment by paOol** [comment]
you have some errors in your code. 
for example

```
const cchain = avalanche.XChain
```
did you mean to do. `const cchain: EVMAPI = avalanche.CChain()` ?

I believe the reason your verify function is not working is because you are calling `makeKey()` and that creates a new address and private key each time. so it's never going to verify the signature of a message you created with a different keyPair.

since there is no error with the keypair methods themselves, I'm closing this issue.
