### ISSUE TITLE
Can anyone help me solve this problem

### ISSUE THREAD

**Issue by cao148** [ava-labs/avalanchejs#354]
Can anyone help me solve this problem
![image](https://user-images.githubusercontent.com/62193059/134321422-104c50d8-43e2-442b-9b56-524e016f8998.png)

I tried to run https://github.com/ava-labs/avalanchejs/blob/master/examples/index/getLastAccepted.ts but this is also wrong

**Comment by cao148** [comment]
> Can anyone help me solve this problem
> ![image](https://user-images.githubusercontent.com/62193059/134321422-104c50d8-43e2-442b-9b56-524e016f8998.png)

I tried to run https://github.com/ava-labs/avalanchejs/blob/master/examples/index/getLastAccepted.ts but this is also wrong

**Comment by paOol** [comment]
There is a type error in that example. I have created a PR for it.

However, for your issue make sure you have indexing enabled on your node(s)

https://docs.avax.network/build/avalanchego-apis/index-api

you can re-open this issue if you still run into errors after enabling indexing.

**Comment by cao148** [comment]
I use the public node provided by you, the avalanchejs library for communication, how do I enable indexing in the js library?
const avalanche = new Avalanche("api.avax-test.network",443,"https",5);

**Comment by cao148** [comment]
https://github.com/ava-labs/avalanchejs/issues/354#issuecomment-925439983

I use the public node provided by you, the avalanchejs library for communication, how do I enable indexing in the js library?
const avalanche = new Avalanche("api.avax-test.network",443,"https",5);

**Comment by paOol** [comment]
our public infrastructure does not support certain features.

For example, keystore functionality, and indexing functionality.

This is intentional, for security and resource purposes. 

if you want to use indexing features, you'll have to run your own node.

here is a guide on how to run Avash (local network)

https://gist.github.com/cgcardona/d125824b8be54ce3073582899cc335ce
