### ISSUE TITLE
Make function static

### ISSUE THREAD

**Issue by kanatliemre** [ava-labs/avalanchejs#425]
https://github.com/ava-labs/avalanchejs/blob/2bedac37aed5327b3535438ba58b6babcdc0cd0a/src/common/secp256k1.ts#L126

This function is very useful and I think it should be made static, accessible from the class. It does not use anything from the class instance.

**Comment by cgcardona** [comment]
This is resolved in https://github.com/ava-labs/avalanchejs/pull/482
