### ISSUE TITLE
Error: expected signature from HT7xU2Ngenf7D4yocz2SAcnNLW7tcyFaQ but got from 7oHnRFRnENxA11UzY27nU5cNQ5MY2draD

### ISSUE THREAD

**Issue by AUQIB92** [ava-labs/avalanchejs#495]
I am trying to  send Avax on fuji testnet, but getting this error
I am trying to do offline signing using mpc
Error: expected signature from HT7xU2Ngenf7D4yocz2SAcnNLW7tcyFaQ but got from 7oHnRFRnENxA11UzY27nU5cNQ5MY2draD

**Comment by cgcardona** [comment]
It sounds like you are trying to sign the transaction with the incorrect key from your local keychain. Can you remove any sensitive bits and share a gist of your code? Thanks
