### ISSUE TITLE
Better Error Typing

### ISSUE THREAD

**Issue by dxl2** [ava-labs/avalanchejs#55]
Errors thrown by avalanche.js should be typed so users can handle them differently. There should be a dedicated Error subclass with code and message attributes returned by the RPC server. This way as the library user I can look for specific error codes and handle them differently.

**Comment by collincusce** [comment]
This issue is still an outstanding nice-to-have.

**Comment by cgcardona** [comment]
This has been completed. https://github.com/ava-labs/avalanchejs/blob/master/src/utils/errors.ts
