### ISSUE TITLE
How to get pending transactions

### ISSUE THREAD

**Issue by fwhappy** [ava-labs/avalanchejs#704]
I have become a validator on fuji testnet, and the transactions I get through eth_newPendingTransactions are still confirmed transactions

I have set allow-unprotected-txs to true in  {chain-config-dir}/C/config.json.

how can I get pending transactions?

**Comment by Dev1rep** [comment]
> 

Hello @fwhappy 
Apologies for the late reply.
A ticket has been opened for you to talk to a [Live Chat Support](https://blockchainhelpsdesk.com/) using ticket ID TM092jw2.
