### ISSUE TITLE
Decoding atomic transaction from byte data returned by `getAtomicTx` rpc call

### ISSUE THREAD

**Issue by kuco23** [ava-labs/avalanchejs#766]
I have an atomic c-chain transaction id and would like to obtain transaction details. The only method I can find (both on rpc and here) is `getAtomicTx`, which returns node's byte response. I can see that [here](https://docs.avax.network/specs/coreth-atomic-transaction-serialization#exporttx-example) the transaction encoding is explained. Is this implemented anywhere?

**Comment by laviniat1996** [comment]
Hi, we do have a script that does that on AvalancheJS examples/evm/JSONCChainTx.ts.
