### ISSUE TITLE
Security: insecure deps are used, switch to better ones

### ISSUE THREAD

**Issue by paulmillr** [ava-labs/avalanchejs#790]
You are using things like elliptic and crypto-browserify, which contain huge amount of code and are not as secure as modern libraries, such as [noble](https://paulmillr.com/noble/).

elliptic had [2 vulnerabilities](https://security.snyk.io/package/npm/elliptic).

**Comment by paulmillr** [comment]
Do you care about cryptography folks? @dfenstermaker

**Comment by bferenc** [comment]
Hey @paulmillr ! Thanks for your comment! The dependencies have been replaced / upgraded in v4.
