### ISSUE TITLE
Support for Node18

### ISSUE THREAD

**Issue by andrew-scott-fischer** [ava-labs/avalanchejs#844]
At present, this [package restricts the NodeJS version to 20](https://github.com/ava-labs/avalanchejs/blob/master/package.json#L78-L80). Is this intensional?

**Comment by andrew-scott-fischer** [comment]
Did you intend to not support Node18?

**Comment by yashutanna** [comment]
+1 https://github.com/ava-labs/avalanchejs/issues/840

**Comment by erictaylor** [comment]
The Node engine version support is intentional.

Node v22 is now active LTS, and v18's maintenance ends mid 2025. If you need Node v18 support, you can run v3 of the library.
