### ISSUE TITLE
I can't deserialize TransformSubnetTx

### ISSUE THREAD

**Issue by hoangong** [ava-labs/avalanchejs#902]
Particularly this transaction in testnet https://subnets-test.avax.network/p-chain/tx/XWUWCYBjXtPkeart1wBFUUVpkbstMSshK4D7xVc99DNkUMNG1

Its raw data is 

> {"jsonrpc":"2.0","result":{"tx":"0x000000000018000000050000000000000000000000000000000000000000000000000000000000000000000000023d9bdac0ed1d761330cf680efdeb1a42159eb387d6d2950c96f7d28f61bbe2aa0000000700000000767e790000000000000000000000000100000001d517ddd7a8cabe414f9069c5c79d39ffebcd431cc4e0dec1ea725a01d78e4505e9aca9a7928edeea69252d6d695481bfc75e44e400000007000000000e4e1c0000000000000000000000000100000001d517ddd7a8cabe414f9069c5c79d39ffebcd431c0000000329aa8e1527bc68499fb7d916487bbc0135d799ad79ef4325b13c048207ea0157000000003d9bdac0ed1d761330cf680efdeb1a42159eb387d6d2950c96f7d28f61bbe2aa0000000500000000054e08400000000100000000fce9634c79785cdcc474c54eec82869f7ab40fc3d83823a42e0ecedeeee1118d000000003d9bdac0ed1d761330cf680efdeb1a42159eb387d6d2950c96f7d28f61bbe2aa0000000500000000accb3ac00000000100000000fce9634c79785cdcc474c54eec82869f7ab40fc3d83823a42e0ecedeeee1118d00000001c4e0dec1ea725a01d78e4505e9aca9a7928edeea69252d6d695481bfc75e44e400000005000000002aea5400000000010000000000000000f41f2c6446af907b7e9a3bbd016a25bdd7e291720e14c9b2c1b8892da56f6ec2c4e0dec1ea725a01d78e4505e9aca9a7928edeea69252d6d695481bfc75e44e4000000000e4e1c00000000002aea540000000000000186a0000000000001d4c000000000000007d000000000002dc6c00012750001e1338000004e20000000000000001905000c35000000000a00000002000000010000000200000004000000090000000153ed70efe552ed72d02fb52f1d48045512879656796495cd45d7cc958e049faf76a213e338456b2b8f7e40e5ca3669b45f627149eea956b310dcd5abed7eb03801000000090000000153ed70efe552ed72d02fb52f1d48045512879656796495cd45d7cc958e049faf76a213e338456b2b8f7e40e5ca3669b45f627149eea956b310dcd5abed7eb03801000000090000000153ed70efe552ed72d02fb52f1d48045512879656796495cd45d7cc958e049faf76a213e338456b2b8f7e40e5ca3669b45f627149eea956b310dcd5abed7eb0380100000009000000023617b66ea21aca709fe5ce1268180d5d1adac438fda806ff164bb32a304a7bd2631b43d67d46f0954b92a36733cd2538e2c2662477c547d96d8aebb646c1f3980153ed70efe552ed72d02fb52f1d48045512879656796495cd45d7cc958e049faf76a213e338456b2b8f7e40e5ca3669b45f627149eea956b310dcd5abed7eb038010e2399c9","encoding":"hex"},"id":1}

I remove codecId and typeId prefix from the data and put it into unit test, it fails with error:

```
couldn't unmarshal interface: unknown type ID 800000
```

I think there is a problem with deserializing `subnetAuth` field

This is the code to reproduce the error:

```
describe("test", () => {
  it("decode transformSubnetTx", () => {
    const bytes = Buffer.from('000000050000000000000000000000000000000000000000000000000000000000000000000000023d9bdac0ed1d761330cf680efdeb1a42159eb387d6d2950c96f7d28f61bbe2aa0000000700000000767e790000000000000000000000000100000001d517ddd7a8cabe414f9069c5c79d39ffebcd431cc4e0dec1ea725a01d78e4505e9aca9a7928edeea69252d6d695481bfc75e44e400000007000000000e4e1c0000000000000000000000000100000001d517ddd7a8cabe414f9069c5c79d39ffebcd431c0000000329aa8e1527bc68499fb7d916487bbc0135d799ad79ef4325b13c048207ea0157000000003d9bdac0ed1d761330cf680efdeb1a42159eb387d6d2950c96f7d28f61bbe2aa0000000500000000054e08400000000100000000fce9634c79785cdcc474c54eec82869f7ab40fc3d83823a42e0ecedeeee1118d000000003d9bdac0ed1d761330cf680efdeb1a42159eb387d6d2950c96f7d28f61bbe2aa0000000500000000accb3ac00000000100000000fce9634c79785cdcc474c54eec82869f7ab40fc3d83823a42e0ecedeeee1118d00000001c4e0dec1ea725a01d78e4505e9aca9a7928edeea69252d6d695481bfc75e44e400000005000000002aea5400000000010000000000000000f41f2c6446af907b7e9a3bbd016a25bdd7e291720e14c9b2c1b8892da56f6ec2c4e0dec1ea725a01d78e4505e9aca9a7928edeea69252d6d695481bfc75e44e4000000000e4e1c00000000002aea540000000000000186a0000000000001d4c000000000000007d000000000002dc6c00012750001e1338000004e20000000000000001905000c35000000000a00000002000000010000000200000004000000090000000153ed70efe552ed72d02fb52f1d48045512879656796495cd45d7cc958e049faf76a213e338456b2b8f7e40e5ca3669b45f627149eea956b310dcd5abed7eb03801000000090000000153ed70efe552ed72d02fb52f1d48045512879656796495cd45d7cc958e049faf76a213e338456b2b8f7e40e5ca3669b45f627149eea956b310dcd5abed7eb03801000000090000000153ed70efe552ed72d02fb52f1d48045512879656796495cd45d7cc958e049faf76a213e338456b2b8f7e40e5ca3669b45f627149eea956b310dcd5abed7eb0380100000009000000023617b66ea21aca709fe5ce1268180d5d1adac438fda806ff164bb32a304a7bd2631b43d67d46f0954b92a36733cd2538e2c2662477c547d96d8aebb646c1f3980153ed70efe552ed72d02fb52f1d48045512879656796495cd45d7cc958e049faf76a213e338456b2b8f7e40e5ca3669b45f627149eea956b310dcd5abed7eb038010e2399c9', 'hex')
    TransformSubnetTx.fromBytes(bytes, testCodec());
  });
});
```

**Comment by bferenc** [comment]
Hi! Thanks for reporting this issue, here's a potential fix: https://github.com/ava-labs/avalanchejs/pull/903

**Comment by hoangong** [comment]
I can confirm the bug is fixed now. thank you for the quick fix.
