### ISSUE TITLE
Missing dist/lib/avalanche.js in the bundle 

### ISSUE THREAD

**Issue by harryEth** [ava-labs/avalanchejs#97]
In the package.json of avalanche (https://github.com/ava-labs/avalanche.js/blob/ab1d22ad5298c4e04fd17abad65316ef21e0f102/package.json#L6) the browser field refers to dist/lib/avalanche.js, but upon checking I don't think that folder exists. Only the dist folder exists, but it doesn't contain a lib folder: https://unpkg.com/browse/avalanche@2.4.3/dist/.

This is causing the issue(https://github.com/ava-labs/avalanche.js/issues/89) and some env will not work well. 

Can anyone help to fix this?

**Comment by collincusce** [comment]
Yes it'll be fixed in the next release. We moved the bundle out of dist because it was causing import conflicts. It's now in web. Thanks for pointing that out!

**Comment by harryEth** [comment]
> Does this fix codesandbox, by the way?

yes, it should fix the codesandbox.

**Comment by collincusce** [comment]
We're planning on removing the "browser" property from the package.json entirely.

**Comment by harryEth** [comment]
Thanks for solving this problem. Closing this.
